#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

#runApplication blockMesh

#add in gmsh meshing
# gmsh -3 -optimize_netgen cylinder.geo -o cylinder.msh -format msh2
runApplication gmshToFoam ./gmsh/g1fOF.msh

# need to specify patches as empty (Contrib modifyPatches https://openfoamwiki.net/index.php/Contrib_modifyPatches). seems like the best way to do this is to fetch the utility from the github repo and compile it in the openfoam-docker shell script (modifyPatches works up til OF v2206).
# probably easier to just go into the file and change the text using sed, stream editor, to change the type of the patches to empty.
sed -i 's/type[[:space:]]*patch/type            wall/g' constant/polyMesh/boundary

sed -i '/back/,/}/ s/type[[:space:]]*wall/type            empty/' constant/polyMesh/boundary                                                                 
sed -i '/front/,/}/ s/type[[:space:]]*wall/type            empty/' constant/polyMesh/boundary


runApplication checkMesh
#runApplication setFields

runApplication $(getApplication)

# runApplication foamToVTK -fields '(U p T)'

#------------------------------------------------------------------------------
# [1] --> FOAM FATAL ERROR: (openfoam-2306)
# Cannot dereference nullptr at index -1 in range [0,0)
# caused by misspecifying the name of the mesh file in gmshToFoam